### PR TITLE
Added governor redmine module

### PR DESCRIPTION
**Pull request by smiklosovic**
@rmpestano

I am ready to merge when you are. Please review this once again and let me know.

It is with all your changes + jira and github bugfixes.

Thanks!

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @smiklosovic,

I think that's it, I will test it after the merge and come back here if something is wrong.

**Comment by smiklosovic** [comment]
@rmpestano in master

let me know if we can release this

**Comment by rmpestano** [comment]
Hi @smiklosovic,

it is working great (didn't tested Jira).

There is only one thing in Governor Github which is that it is trying to close closed issues. Do you think it is aproblem? example see last 3 comments of the following issue: https://github.com/rmpestano/design-patterns/issues/1/#issuecomment-167610281

For governor redmine I'm checking if issue isn't closed and then I add the comment.

I can open another PR if you think it is an issue.

**Comment by smiklosovic** [comment]
closing closed issue is definitely a problem, could you look into that more closely please? it would be awesome if jira was tested as well

i do not have time for deal with this, i can wait ....

**Comment by rmpestano** [comment]
Sure, I'll look into this. I also will see jira, do we have a public Jira to test governor? otherwise I will install it locally.

**Comment by smiklosovic** [comment]
no, there is not public jira but that one in issues.jboss.org. I tested it there.

**Pull request merged**
