### PR TITLE
[relates #30] Fix maven-checkstyle-plugin configuration

### PR DESCRIPTION
**Pull request by basovnik**
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian-governor/32)

### CODE REVIEW

**Comment by smiklosovic** [comment]
it is still marked as failed

**Comment by smiklosovic** [comment]
github tests are failing because we kind of hit some api rate limits, not sure how to repair it, maybe just ignore them or put them to some profile

**Comment by basovnik** [comment]
There can be only 60 requests per hour [1] when you are unauthorized user. So when you try to fix a pull request (`git commit --amend`) then Travic-CI is executed again and then the count of requests exceeds the limit. So it is sufficient to wait one hour run Travis-CI job again.


[1] https://developer.github.com/v3/#rate-limiting

**Comment by smiklosovic** [comment]
so what's the reason it fails when we are using more than 60?

**Comment by basovnik** [comment]
It works now. I just waited one hour... Could you merge it please?

**Comment by bartoszmajsak** [comment]
@smiklosovic if you are busy and it's urgent for @basovnik I can take care of it.

**Comment by bartoszmajsak** [comment]
:)

**Pull request merged**
